#!/bin/bash
# ========================================================================================
# EJEMPLO DE USO DEL INICIALIZADOR
# ========================================================================================
# Este script muestra cómo usar el inicializador de template con valores de ejemplo
# ========================================================================================

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║         EJEMPLO DE USO - INICIALIZADOR DE TEMPLATE           ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "Este es un ejemplo de cómo usar el inicializador del template."
echo "Los valores mostrados son ejemplos, tú puedes usar los tuyos."
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "EJEMPLO 1: Proyecto simple"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Nombre del proyecto: TaskManager"
echo "Package base: com.acme.taskmanager"
echo "Application ID: [usar el mismo que package]"
echo "Nombre visible: Task Manager"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "EJEMPLO 2: Proyecto con dominio personalizado"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Nombre del proyecto: WeatherApp"
echo "Package base: io.github.myuser.weather"
echo "Application ID: [usar el mismo que package]"
echo "Nombre visible: Weather Forecast"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "EJEMPLO 3: Proyecto con Application ID diferente"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Nombre del proyecto: ShoppingCart"
echo "Package base: com.mycompany.internal.shop"
echo "Application ID: com.mycompany.shop"
echo "Nombre visible: My Shopping App"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Para inicializar tu proyecto, ejecuta:"
echo ""
echo "  ./Scripts/init-project.sh"
echo ""
echo "Y sigue las instrucciones interactivas."
echo ""

